/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MapRouteImport } from './routes/map'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiStoresRouteImport } from './routes/api/stores'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPromotionsRouteImport } from './routes/api/promotions'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiStoresSlugRouteImport } from './routes/api/stores.$slug'
import { Route as ApiStoreStatsRouteImport } from './routes/api/store.stats'
import { Route as ApiStoreQueriesRouteImport } from './routes/api/store.queries'
import { Route as ApiStorePromotionsRouteImport } from './routes/api/store.promotions'
import { Route as ApiStoreProfileRouteImport } from './routes/api/store.profile'
import { Route as ApiStoreProductsRouteImport } from './routes/api/store.products'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'
import { Route as ApiClientReviewsRouteImport } from './routes/api/client.reviews'
import { Route as ApiClientQueriesRouteImport } from './routes/api/client.queries'
import { Route as ApiClientFavoritesRouteImport } from './routes/api/client.favorites'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai.search'
import { Route as ApiAiPromotionCopyRouteImport } from './routes/api/ai.promotion-copy'
import { Route as ApiAiProductDescriptionRouteImport } from './routes/api/ai.product-description'
import { Route as ApiAiPriceSuggestionRouteImport } from './routes/api/ai.price-suggestion'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin.users'
import { Route as ApiAdminStoresRouteImport } from './routes/api/admin.stores'
import { Route as ApiAdminReportsRouteImport } from './routes/api/admin.reports'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin.dashboard'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin.categories'
import { Route as ApiStoreQueriesIdRouteImport } from './routes/api/store.queries.$id'
import { Route as ApiStorePromotionsIdRouteImport } from './routes/api/store.promotions.$id'
import { Route as ApiStoreProductsIdRouteImport } from './routes/api/store.products.$id'
import { Route as ApiClientFavoritesIdRouteImport } from './routes/api/client.favorites.$id'
import { Route as ApiAdminStoresIdStatusRouteImport } from './routes/api/admin.stores.$id.status'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresRoute = ApiStoresRouteImport.update({
  id: '/api/stores',
  path: '/api/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromotionsRoute = ApiPromotionsRouteImport.update({
  id: '/api/promotions',
  path: '/api/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresSlugRoute = ApiStoresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiStoresRoute,
} as any)
const ApiStoreStatsRoute = ApiStoreStatsRouteImport.update({
  id: '/api/store/stats',
  path: '/api/store/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreQueriesRoute = ApiStoreQueriesRouteImport.update({
  id: '/api/store/queries',
  path: '/api/store/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorePromotionsRoute = ApiStorePromotionsRouteImport.update({
  id: '/api/store/promotions',
  path: '/api/store/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreProfileRoute = ApiStoreProfileRouteImport.update({
  id: '/api/store/profile',
  path: '/api/store/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreProductsRoute = ApiStoreProductsRouteImport.update({
  id: '/api/store/products',
  path: '/api/store/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/api/products/$id',
  path: '/api/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientReviewsRoute = ApiClientReviewsRouteImport.update({
  id: '/api/client/reviews',
  path: '/api/client/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientQueriesRoute = ApiClientQueriesRouteImport.update({
  id: '/api/client/queries',
  path: '/api/client/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientFavoritesRoute = ApiClientFavoritesRouteImport.update({
  id: '/api/client/favorites',
  path: '/api/client/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai/search',
  path: '/api/ai/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPromotionCopyRoute = ApiAiPromotionCopyRouteImport.update({
  id: '/api/ai/promotion-copy',
  path: '/api/ai/promotion-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiProductDescriptionRoute = ApiAiProductDescriptionRouteImport.update({
  id: '/api/ai/product-description',
  path: '/api/ai/product-description',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPriceSuggestionRoute = ApiAiPriceSuggestionRouteImport.update({
  id: '/api/ai/price-suggestion',
  path: '/api/ai/price-suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStoresRoute = ApiAdminStoresRouteImport.update({
  id: '/api/admin/stores',
  path: '/api/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportsRoute = ApiAdminReportsRouteImport.update({
  id: '/api/admin/reports',
  path: '/api/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreQueriesIdRoute = ApiStoreQueriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStoreQueriesRoute,
} as any)
const ApiStorePromotionsIdRoute = ApiStorePromotionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStorePromotionsRoute,
} as any)
const ApiStoreProductsIdRoute = ApiStoreProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStoreProductsRoute,
} as any)
const ApiClientFavoritesIdRoute = ApiClientFavoritesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientFavoritesRoute,
} as any)
const ApiAdminStoresIdStatusRoute = ApiAdminStoresIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiAdminStoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/promotions': typeof ApiPromotionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/reports': typeof ApiAdminReportsRoute
  '/api/admin/stores': typeof ApiAdminStoresRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/price-suggestion': typeof ApiAiPriceSuggestionRoute
  '/api/ai/product-description': typeof ApiAiProductDescriptionRoute
  '/api/ai/promotion-copy': typeof ApiAiPromotionCopyRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/client/favorites': typeof ApiClientFavoritesRouteWithChildren
  '/api/client/queries': typeof ApiClientQueriesRoute
  '/api/client/reviews': typeof ApiClientReviewsRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/store/products': typeof ApiStoreProductsRouteWithChildren
  '/api/store/profile': typeof ApiStoreProfileRoute
  '/api/store/promotions': typeof ApiStorePromotionsRouteWithChildren
  '/api/store/queries': typeof ApiStoreQueriesRouteWithChildren
  '/api/store/stats': typeof ApiStoreStatsRoute
  '/api/stores/$slug': typeof ApiStoresSlugRoute
  '/api/client/favorites/$id': typeof ApiClientFavoritesIdRoute
  '/api/store/products/$id': typeof ApiStoreProductsIdRoute
  '/api/store/promotions/$id': typeof ApiStorePromotionsIdRoute
  '/api/store/queries/$id': typeof ApiStoreQueriesIdRoute
  '/api/admin/stores/$id/status': typeof ApiAdminStoresIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/promotions': typeof ApiPromotionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/reports': typeof ApiAdminReportsRoute
  '/api/admin/stores': typeof ApiAdminStoresRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/price-suggestion': typeof ApiAiPriceSuggestionRoute
  '/api/ai/product-description': typeof ApiAiProductDescriptionRoute
  '/api/ai/promotion-copy': typeof ApiAiPromotionCopyRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/client/favorites': typeof ApiClientFavoritesRouteWithChildren
  '/api/client/queries': typeof ApiClientQueriesRoute
  '/api/client/reviews': typeof ApiClientReviewsRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/store/products': typeof ApiStoreProductsRouteWithChildren
  '/api/store/profile': typeof ApiStoreProfileRoute
  '/api/store/promotions': typeof ApiStorePromotionsRouteWithChildren
  '/api/store/queries': typeof ApiStoreQueriesRouteWithChildren
  '/api/store/stats': typeof ApiStoreStatsRoute
  '/api/stores/$slug': typeof ApiStoresSlugRoute
  '/api/client/favorites/$id': typeof ApiClientFavoritesIdRoute
  '/api/store/products/$id': typeof ApiStoreProductsIdRoute
  '/api/store/promotions/$id': typeof ApiStorePromotionsIdRoute
  '/api/store/queries/$id': typeof ApiStoreQueriesIdRoute
  '/api/admin/stores/$id/status': typeof ApiAdminStoresIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/promotions': typeof ApiPromotionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/reports': typeof ApiAdminReportsRoute
  '/api/admin/stores': typeof ApiAdminStoresRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/price-suggestion': typeof ApiAiPriceSuggestionRoute
  '/api/ai/product-description': typeof ApiAiProductDescriptionRoute
  '/api/ai/promotion-copy': typeof ApiAiPromotionCopyRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/client/favorites': typeof ApiClientFavoritesRouteWithChildren
  '/api/client/queries': typeof ApiClientQueriesRoute
  '/api/client/reviews': typeof ApiClientReviewsRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/store/products': typeof ApiStoreProductsRouteWithChildren
  '/api/store/profile': typeof ApiStoreProfileRoute
  '/api/store/promotions': typeof ApiStorePromotionsRouteWithChildren
  '/api/store/queries': typeof ApiStoreQueriesRouteWithChildren
  '/api/store/stats': typeof ApiStoreStatsRoute
  '/api/stores/$slug': typeof ApiStoresSlugRoute
  '/api/client/favorites/$id': typeof ApiClientFavoritesIdRoute
  '/api/store/products/$id': typeof ApiStoreProductsIdRoute
  '/api/store/promotions/$id': typeof ApiStorePromotionsIdRoute
  '/api/store/queries/$id': typeof ApiStoreQueriesIdRoute
  '/api/admin/stores/$id/status': typeof ApiAdminStoresIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/api/categories'
    | '/api/promotions'
    | '/api/search'
    | '/api/stores'
    | '/product/$id'
    | '/store/$slug'
    | '/api/admin/categories'
    | '/api/admin/dashboard'
    | '/api/admin/reports'
    | '/api/admin/stores'
    | '/api/admin/users'
    | '/api/ai/price-suggestion'
    | '/api/ai/product-description'
    | '/api/ai/promotion-copy'
    | '/api/ai/search'
    | '/api/client/favorites'
    | '/api/client/queries'
    | '/api/client/reviews'
    | '/api/products/$id'
    | '/api/store/products'
    | '/api/store/profile'
    | '/api/store/promotions'
    | '/api/store/queries'
    | '/api/store/stats'
    | '/api/stores/$slug'
    | '/api/client/favorites/$id'
    | '/api/store/products/$id'
    | '/api/store/promotions/$id'
    | '/api/store/queries/$id'
    | '/api/admin/stores/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/api/categories'
    | '/api/promotions'
    | '/api/search'
    | '/api/stores'
    | '/product/$id'
    | '/store/$slug'
    | '/api/admin/categories'
    | '/api/admin/dashboard'
    | '/api/admin/reports'
    | '/api/admin/stores'
    | '/api/admin/users'
    | '/api/ai/price-suggestion'
    | '/api/ai/product-description'
    | '/api/ai/promotion-copy'
    | '/api/ai/search'
    | '/api/client/favorites'
    | '/api/client/queries'
    | '/api/client/reviews'
    | '/api/products/$id'
    | '/api/store/products'
    | '/api/store/profile'
    | '/api/store/promotions'
    | '/api/store/queries'
    | '/api/store/stats'
    | '/api/stores/$slug'
    | '/api/client/favorites/$id'
    | '/api/store/products/$id'
    | '/api/store/promotions/$id'
    | '/api/store/queries/$id'
    | '/api/admin/stores/$id/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/api/categories'
    | '/api/promotions'
    | '/api/search'
    | '/api/stores'
    | '/product/$id'
    | '/store/$slug'
    | '/api/admin/categories'
    | '/api/admin/dashboard'
    | '/api/admin/reports'
    | '/api/admin/stores'
    | '/api/admin/users'
    | '/api/ai/price-suggestion'
    | '/api/ai/product-description'
    | '/api/ai/promotion-copy'
    | '/api/ai/search'
    | '/api/client/favorites'
    | '/api/client/queries'
    | '/api/client/reviews'
    | '/api/products/$id'
    | '/api/store/products'
    | '/api/store/profile'
    | '/api/store/promotions'
    | '/api/store/queries'
    | '/api/store/stats'
    | '/api/stores/$slug'
    | '/api/client/favorites/$id'
    | '/api/store/products/$id'
    | '/api/store/promotions/$id'
    | '/api/store/queries/$id'
    | '/api/admin/stores/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiPromotionsRoute: typeof ApiPromotionsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStoresRoute: typeof ApiStoresRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminReportsRoute: typeof ApiAdminReportsRoute
  ApiAdminStoresRoute: typeof ApiAdminStoresRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAiPriceSuggestionRoute: typeof ApiAiPriceSuggestionRoute
  ApiAiProductDescriptionRoute: typeof ApiAiProductDescriptionRoute
  ApiAiPromotionCopyRoute: typeof ApiAiPromotionCopyRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiClientFavoritesRoute: typeof ApiClientFavoritesRouteWithChildren
  ApiClientQueriesRoute: typeof ApiClientQueriesRoute
  ApiClientReviewsRoute: typeof ApiClientReviewsRoute
  ApiProductsIdRoute: typeof ApiProductsIdRoute
  ApiStoreProductsRoute: typeof ApiStoreProductsRouteWithChildren
  ApiStoreProfileRoute: typeof ApiStoreProfileRoute
  ApiStorePromotionsRoute: typeof ApiStorePromotionsRouteWithChildren
  ApiStoreQueriesRoute: typeof ApiStoreQueriesRouteWithChildren
  ApiStoreStatsRoute: typeof ApiStoreStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores': {
      id: '/api/stores'
      path: '/api/stores'
      fullPath: '/api/stores'
      preLoaderRoute: typeof ApiStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promotions': {
      id: '/api/promotions'
      path: '/api/promotions'
      fullPath: '/api/promotions'
      preLoaderRoute: typeof ApiPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores/$slug': {
      id: '/api/stores/$slug'
      path: '/$slug'
      fullPath: '/api/stores/$slug'
      preLoaderRoute: typeof ApiStoresSlugRouteImport
      parentRoute: typeof ApiStoresRoute
    }
    '/api/store/stats': {
      id: '/api/store/stats'
      path: '/api/store/stats'
      fullPath: '/api/store/stats'
      preLoaderRoute: typeof ApiStoreStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/queries': {
      id: '/api/store/queries'
      path: '/api/store/queries'
      fullPath: '/api/store/queries'
      preLoaderRoute: typeof ApiStoreQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/promotions': {
      id: '/api/store/promotions'
      path: '/api/store/promotions'
      fullPath: '/api/store/promotions'
      preLoaderRoute: typeof ApiStorePromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/profile': {
      id: '/api/store/profile'
      path: '/api/store/profile'
      fullPath: '/api/store/profile'
      preLoaderRoute: typeof ApiStoreProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/products': {
      id: '/api/store/products'
      path: '/api/store/products'
      fullPath: '/api/store/products'
      preLoaderRoute: typeof ApiStoreProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/api/products/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client/reviews': {
      id: '/api/client/reviews'
      path: '/api/client/reviews'
      fullPath: '/api/client/reviews'
      preLoaderRoute: typeof ApiClientReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client/queries': {
      id: '/api/client/queries'
      path: '/api/client/queries'
      fullPath: '/api/client/queries'
      preLoaderRoute: typeof ApiClientQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client/favorites': {
      id: '/api/client/favorites'
      path: '/api/client/favorites'
      fullPath: '/api/client/favorites'
      preLoaderRoute: typeof ApiClientFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/search': {
      id: '/api/ai/search'
      path: '/api/ai/search'
      fullPath: '/api/ai/search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/promotion-copy': {
      id: '/api/ai/promotion-copy'
      path: '/api/ai/promotion-copy'
      fullPath: '/api/ai/promotion-copy'
      preLoaderRoute: typeof ApiAiPromotionCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/product-description': {
      id: '/api/ai/product-description'
      path: '/api/ai/product-description'
      fullPath: '/api/ai/product-description'
      preLoaderRoute: typeof ApiAiProductDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/price-suggestion': {
      id: '/api/ai/price-suggestion'
      path: '/api/ai/price-suggestion'
      fullPath: '/api/ai/price-suggestion'
      preLoaderRoute: typeof ApiAiPriceSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stores': {
      id: '/api/admin/stores'
      path: '/api/admin/stores'
      fullPath: '/api/admin/stores'
      preLoaderRoute: typeof ApiAdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports': {
      id: '/api/admin/reports'
      path: '/api/admin/reports'
      fullPath: '/api/admin/reports'
      preLoaderRoute: typeof ApiAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/queries/$id': {
      id: '/api/store/queries/$id'
      path: '/$id'
      fullPath: '/api/store/queries/$id'
      preLoaderRoute: typeof ApiStoreQueriesIdRouteImport
      parentRoute: typeof ApiStoreQueriesRoute
    }
    '/api/store/promotions/$id': {
      id: '/api/store/promotions/$id'
      path: '/$id'
      fullPath: '/api/store/promotions/$id'
      preLoaderRoute: typeof ApiStorePromotionsIdRouteImport
      parentRoute: typeof ApiStorePromotionsRoute
    }
    '/api/store/products/$id': {
      id: '/api/store/products/$id'
      path: '/$id'
      fullPath: '/api/store/products/$id'
      preLoaderRoute: typeof ApiStoreProductsIdRouteImport
      parentRoute: typeof ApiStoreProductsRoute
    }
    '/api/client/favorites/$id': {
      id: '/api/client/favorites/$id'
      path: '/$id'
      fullPath: '/api/client/favorites/$id'
      preLoaderRoute: typeof ApiClientFavoritesIdRouteImport
      parentRoute: typeof ApiClientFavoritesRoute
    }
    '/api/admin/stores/$id/status': {
      id: '/api/admin/stores/$id/status'
      path: '/$id/status'
      fullPath: '/api/admin/stores/$id/status'
      preLoaderRoute: typeof ApiAdminStoresIdStatusRouteImport
      parentRoute: typeof ApiAdminStoresRoute
    }
  }
}

interface ApiStoresRouteChildren {
  ApiStoresSlugRoute: typeof ApiStoresSlugRoute
}

const ApiStoresRouteChildren: ApiStoresRouteChildren = {
  ApiStoresSlugRoute: ApiStoresSlugRoute,
}

const ApiStoresRouteWithChildren = ApiStoresRoute._addFileChildren(
  ApiStoresRouteChildren,
)

interface ApiAdminStoresRouteChildren {
  ApiAdminStoresIdStatusRoute: typeof ApiAdminStoresIdStatusRoute
}

const ApiAdminStoresRouteChildren: ApiAdminStoresRouteChildren = {
  ApiAdminStoresIdStatusRoute: ApiAdminStoresIdStatusRoute,
}

const ApiAdminStoresRouteWithChildren = ApiAdminStoresRoute._addFileChildren(
  ApiAdminStoresRouteChildren,
)

interface ApiClientFavoritesRouteChildren {
  ApiClientFavoritesIdRoute: typeof ApiClientFavoritesIdRoute
}

const ApiClientFavoritesRouteChildren: ApiClientFavoritesRouteChildren = {
  ApiClientFavoritesIdRoute: ApiClientFavoritesIdRoute,
}

const ApiClientFavoritesRouteWithChildren =
  ApiClientFavoritesRoute._addFileChildren(ApiClientFavoritesRouteChildren)

interface ApiStoreProductsRouteChildren {
  ApiStoreProductsIdRoute: typeof ApiStoreProductsIdRoute
}

const ApiStoreProductsRouteChildren: ApiStoreProductsRouteChildren = {
  ApiStoreProductsIdRoute: ApiStoreProductsIdRoute,
}

const ApiStoreProductsRouteWithChildren =
  ApiStoreProductsRoute._addFileChildren(ApiStoreProductsRouteChildren)

interface ApiStorePromotionsRouteChildren {
  ApiStorePromotionsIdRoute: typeof ApiStorePromotionsIdRoute
}

const ApiStorePromotionsRouteChildren: ApiStorePromotionsRouteChildren = {
  ApiStorePromotionsIdRoute: ApiStorePromotionsIdRoute,
}

const ApiStorePromotionsRouteWithChildren =
  ApiStorePromotionsRoute._addFileChildren(ApiStorePromotionsRouteChildren)

interface ApiStoreQueriesRouteChildren {
  ApiStoreQueriesIdRoute: typeof ApiStoreQueriesIdRoute
}

const ApiStoreQueriesRouteChildren: ApiStoreQueriesRouteChildren = {
  ApiStoreQueriesIdRoute: ApiStoreQueriesIdRoute,
}

const ApiStoreQueriesRouteWithChildren = ApiStoreQueriesRoute._addFileChildren(
  ApiStoreQueriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiPromotionsRoute: ApiPromotionsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStoresRoute: ApiStoresRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
  StoreSlugRoute: StoreSlugRoute,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminReportsRoute: ApiAdminReportsRoute,
  ApiAdminStoresRoute: ApiAdminStoresRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAiPriceSuggestionRoute: ApiAiPriceSuggestionRoute,
  ApiAiProductDescriptionRoute: ApiAiProductDescriptionRoute,
  ApiAiPromotionCopyRoute: ApiAiPromotionCopyRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiClientFavoritesRoute: ApiClientFavoritesRouteWithChildren,
  ApiClientQueriesRoute: ApiClientQueriesRoute,
  ApiClientReviewsRoute: ApiClientReviewsRoute,
  ApiProductsIdRoute: ApiProductsIdRoute,
  ApiStoreProductsRoute: ApiStoreProductsRouteWithChildren,
  ApiStoreProfileRoute: ApiStoreProfileRoute,
  ApiStorePromotionsRoute: ApiStorePromotionsRouteWithChildren,
  ApiStoreQueriesRoute: ApiStoreQueriesRouteWithChildren,
  ApiStoreStatsRoute: ApiStoreStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
