/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStoresRouteImport } from './routes/api/stores'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPromotionsRouteImport } from './routes/api/promotions'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiStoresSlugRouteImport } from './routes/api/stores.$slug'
import { Route as ApiStoreStatsRouteImport } from './routes/api/store.stats'
import { Route as ApiStoreQueriesRouteImport } from './routes/api/store.queries'
import { Route as ApiStorePromotionsRouteImport } from './routes/api/store.promotions'
import { Route as ApiStoreProfileRouteImport } from './routes/api/store.profile'
import { Route as ApiStoreProductsRouteImport } from './routes/api/store.products'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'
import { Route as ApiStoreQueriesIdRouteImport } from './routes/api/store.queries.$id'
import { Route as ApiStorePromotionsIdRouteImport } from './routes/api/store.promotions.$id'
import { Route as ApiStoreProductsIdRouteImport } from './routes/api/store.products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresRoute = ApiStoresRouteImport.update({
  id: '/api/stores',
  path: '/api/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromotionsRoute = ApiPromotionsRouteImport.update({
  id: '/api/promotions',
  path: '/api/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresSlugRoute = ApiStoresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiStoresRoute,
} as any)
const ApiStoreStatsRoute = ApiStoreStatsRouteImport.update({
  id: '/api/store/stats',
  path: '/api/store/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreQueriesRoute = ApiStoreQueriesRouteImport.update({
  id: '/api/store/queries',
  path: '/api/store/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorePromotionsRoute = ApiStorePromotionsRouteImport.update({
  id: '/api/store/promotions',
  path: '/api/store/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreProfileRoute = ApiStoreProfileRouteImport.update({
  id: '/api/store/profile',
  path: '/api/store/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreProductsRoute = ApiStoreProductsRouteImport.update({
  id: '/api/store/products',
  path: '/api/store/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/api/products/$id',
  path: '/api/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreQueriesIdRoute = ApiStoreQueriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStoreQueriesRoute,
} as any)
const ApiStorePromotionsIdRoute = ApiStorePromotionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStorePromotionsRoute,
} as any)
const ApiStoreProductsIdRoute = ApiStoreProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStoreProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/promotions': typeof ApiPromotionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRouteWithChildren
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/store/products': typeof ApiStoreProductsRouteWithChildren
  '/api/store/profile': typeof ApiStoreProfileRoute
  '/api/store/promotions': typeof ApiStorePromotionsRouteWithChildren
  '/api/store/queries': typeof ApiStoreQueriesRouteWithChildren
  '/api/store/stats': typeof ApiStoreStatsRoute
  '/api/stores/$slug': typeof ApiStoresSlugRoute
  '/api/store/products/$id': typeof ApiStoreProductsIdRoute
  '/api/store/promotions/$id': typeof ApiStorePromotionsIdRoute
  '/api/store/queries/$id': typeof ApiStoreQueriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/promotions': typeof ApiPromotionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRouteWithChildren
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/store/products': typeof ApiStoreProductsRouteWithChildren
  '/api/store/profile': typeof ApiStoreProfileRoute
  '/api/store/promotions': typeof ApiStorePromotionsRouteWithChildren
  '/api/store/queries': typeof ApiStoreQueriesRouteWithChildren
  '/api/store/stats': typeof ApiStoreStatsRoute
  '/api/stores/$slug': typeof ApiStoresSlugRoute
  '/api/store/products/$id': typeof ApiStoreProductsIdRoute
  '/api/store/promotions/$id': typeof ApiStorePromotionsIdRoute
  '/api/store/queries/$id': typeof ApiStoreQueriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/promotions': typeof ApiPromotionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRouteWithChildren
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/store/products': typeof ApiStoreProductsRouteWithChildren
  '/api/store/profile': typeof ApiStoreProfileRoute
  '/api/store/promotions': typeof ApiStorePromotionsRouteWithChildren
  '/api/store/queries': typeof ApiStoreQueriesRouteWithChildren
  '/api/store/stats': typeof ApiStoreStatsRoute
  '/api/stores/$slug': typeof ApiStoresSlugRoute
  '/api/store/products/$id': typeof ApiStoreProductsIdRoute
  '/api/store/promotions/$id': typeof ApiStorePromotionsIdRoute
  '/api/store/queries/$id': typeof ApiStoreQueriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/categories'
    | '/api/promotions'
    | '/api/search'
    | '/api/stores'
    | '/api/products/$id'
    | '/api/store/products'
    | '/api/store/profile'
    | '/api/store/promotions'
    | '/api/store/queries'
    | '/api/store/stats'
    | '/api/stores/$slug'
    | '/api/store/products/$id'
    | '/api/store/promotions/$id'
    | '/api/store/queries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/categories'
    | '/api/promotions'
    | '/api/search'
    | '/api/stores'
    | '/api/products/$id'
    | '/api/store/products'
    | '/api/store/profile'
    | '/api/store/promotions'
    | '/api/store/queries'
    | '/api/store/stats'
    | '/api/stores/$slug'
    | '/api/store/products/$id'
    | '/api/store/promotions/$id'
    | '/api/store/queries/$id'
  id:
    | '__root__'
    | '/'
    | '/api/categories'
    | '/api/promotions'
    | '/api/search'
    | '/api/stores'
    | '/api/products/$id'
    | '/api/store/products'
    | '/api/store/profile'
    | '/api/store/promotions'
    | '/api/store/queries'
    | '/api/store/stats'
    | '/api/stores/$slug'
    | '/api/store/products/$id'
    | '/api/store/promotions/$id'
    | '/api/store/queries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiPromotionsRoute: typeof ApiPromotionsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStoresRoute: typeof ApiStoresRouteWithChildren
  ApiProductsIdRoute: typeof ApiProductsIdRoute
  ApiStoreProductsRoute: typeof ApiStoreProductsRouteWithChildren
  ApiStoreProfileRoute: typeof ApiStoreProfileRoute
  ApiStorePromotionsRoute: typeof ApiStorePromotionsRouteWithChildren
  ApiStoreQueriesRoute: typeof ApiStoreQueriesRouteWithChildren
  ApiStoreStatsRoute: typeof ApiStoreStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores': {
      id: '/api/stores'
      path: '/api/stores'
      fullPath: '/api/stores'
      preLoaderRoute: typeof ApiStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promotions': {
      id: '/api/promotions'
      path: '/api/promotions'
      fullPath: '/api/promotions'
      preLoaderRoute: typeof ApiPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores/$slug': {
      id: '/api/stores/$slug'
      path: '/$slug'
      fullPath: '/api/stores/$slug'
      preLoaderRoute: typeof ApiStoresSlugRouteImport
      parentRoute: typeof ApiStoresRoute
    }
    '/api/store/stats': {
      id: '/api/store/stats'
      path: '/api/store/stats'
      fullPath: '/api/store/stats'
      preLoaderRoute: typeof ApiStoreStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/queries': {
      id: '/api/store/queries'
      path: '/api/store/queries'
      fullPath: '/api/store/queries'
      preLoaderRoute: typeof ApiStoreQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/promotions': {
      id: '/api/store/promotions'
      path: '/api/store/promotions'
      fullPath: '/api/store/promotions'
      preLoaderRoute: typeof ApiStorePromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/profile': {
      id: '/api/store/profile'
      path: '/api/store/profile'
      fullPath: '/api/store/profile'
      preLoaderRoute: typeof ApiStoreProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/products': {
      id: '/api/store/products'
      path: '/api/store/products'
      fullPath: '/api/store/products'
      preLoaderRoute: typeof ApiStoreProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/api/products/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/queries/$id': {
      id: '/api/store/queries/$id'
      path: '/$id'
      fullPath: '/api/store/queries/$id'
      preLoaderRoute: typeof ApiStoreQueriesIdRouteImport
      parentRoute: typeof ApiStoreQueriesRoute
    }
    '/api/store/promotions/$id': {
      id: '/api/store/promotions/$id'
      path: '/$id'
      fullPath: '/api/store/promotions/$id'
      preLoaderRoute: typeof ApiStorePromotionsIdRouteImport
      parentRoute: typeof ApiStorePromotionsRoute
    }
    '/api/store/products/$id': {
      id: '/api/store/products/$id'
      path: '/$id'
      fullPath: '/api/store/products/$id'
      preLoaderRoute: typeof ApiStoreProductsIdRouteImport
      parentRoute: typeof ApiStoreProductsRoute
    }
  }
}

interface ApiStoresRouteChildren {
  ApiStoresSlugRoute: typeof ApiStoresSlugRoute
}

const ApiStoresRouteChildren: ApiStoresRouteChildren = {
  ApiStoresSlugRoute: ApiStoresSlugRoute,
}

const ApiStoresRouteWithChildren = ApiStoresRoute._addFileChildren(
  ApiStoresRouteChildren,
)

interface ApiStoreProductsRouteChildren {
  ApiStoreProductsIdRoute: typeof ApiStoreProductsIdRoute
}

const ApiStoreProductsRouteChildren: ApiStoreProductsRouteChildren = {
  ApiStoreProductsIdRoute: ApiStoreProductsIdRoute,
}

const ApiStoreProductsRouteWithChildren =
  ApiStoreProductsRoute._addFileChildren(ApiStoreProductsRouteChildren)

interface ApiStorePromotionsRouteChildren {
  ApiStorePromotionsIdRoute: typeof ApiStorePromotionsIdRoute
}

const ApiStorePromotionsRouteChildren: ApiStorePromotionsRouteChildren = {
  ApiStorePromotionsIdRoute: ApiStorePromotionsIdRoute,
}

const ApiStorePromotionsRouteWithChildren =
  ApiStorePromotionsRoute._addFileChildren(ApiStorePromotionsRouteChildren)

interface ApiStoreQueriesRouteChildren {
  ApiStoreQueriesIdRoute: typeof ApiStoreQueriesIdRoute
}

const ApiStoreQueriesRouteChildren: ApiStoreQueriesRouteChildren = {
  ApiStoreQueriesIdRoute: ApiStoreQueriesIdRoute,
}

const ApiStoreQueriesRouteWithChildren = ApiStoreQueriesRoute._addFileChildren(
  ApiStoreQueriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiPromotionsRoute: ApiPromotionsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStoresRoute: ApiStoresRouteWithChildren,
  ApiProductsIdRoute: ApiProductsIdRoute,
  ApiStoreProductsRoute: ApiStoreProductsRouteWithChildren,
  ApiStoreProfileRoute: ApiStoreProfileRoute,
  ApiStorePromotionsRoute: ApiStorePromotionsRouteWithChildren,
  ApiStoreQueriesRoute: ApiStoreQueriesRouteWithChildren,
  ApiStoreStatsRoute: ApiStoreStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
