-- Mercanta operational marketplace foundation. This migration is additive and
-- intentionally keeps checkout payments outside the current release.

CREATE TABLE IF NOT EXISTS public.ciudades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  departamento TEXT NOT NULL,
  pais_codigo CHAR(2) NOT NULL DEFAULT 'CO',
  moneda_codigo CHAR(3) NOT NULL DEFAULT 'COP',
  lat NUMERIC(9,6),
  lng NUMERIC(9,6),
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.zonas
  ADD COLUMN IF NOT EXISTS ciudad_id BIGINT REFERENCES public.ciudades(id) ON DELETE SET NULL;

ALTER TABLE public.comercios
  ADD COLUMN IF NOT EXISTS ciudad_id BIGINT REFERENCES public.ciudades(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS onboarding_completado_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS verificado_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS verificado_por UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_zonas_ciudad ON public.zonas(ciudad_id) WHERE activa = TRUE;
CREATE INDEX IF NOT EXISTS idx_comercios_ciudad ON public.comercios(ciudad_id)
  WHERE estado = 'activo' AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.comercio_miembros (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  comercio_id UUID NOT NULL REFERENCES public.comercios(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rol TEXT NOT NULL CHECK (rol IN ('owner', 'manager', 'catalogo', 'atencion')),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (comercio_id, profile_id)
);

CREATE INDEX IF NOT EXISTS idx_comercio_miembros_profile
  ON public.comercio_miembros(profile_id) WHERE activo = TRUE;

CREATE TABLE IF NOT EXISTS public.comercio_suscripciones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  comercio_id UUID NOT NULL REFERENCES public.comercios(id) ON DELETE CASCADE,
  plan_id BIGINT NOT NULL REFERENCES public.planes_suscripcion(id),
  estado TEXT NOT NULL CHECK (estado IN ('trial', 'activa', 'vencida', 'cancelada', 'suspendida')),
  inicia_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  vence_at TIMESTAMPTZ,
  cancelada_at TIMESTAMPTZ,
  notas TEXT,
  creada_por UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_suscripcion_operativa_por_comercio
  ON public.comercio_suscripciones(comercio_id)
  WHERE estado IN ('trial', 'activa', 'suspendida');
CREATE INDEX IF NOT EXISTS idx_suscripciones_vencimiento
  ON public.comercio_suscripciones(vence_at) WHERE estado IN ('trial', 'activa');

CREATE TABLE IF NOT EXISTS public.pedidos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  cliente_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  comercio_id UUID NOT NULL REFERENCES public.comercios(id) ON DELETE RESTRICT,
  estado TEXT NOT NULL DEFAULT 'solicitado' CHECK (estado IN (
    'solicitado', 'aceptado', 'rechazado', 'preparando', 'listo',
    'en_camino', 'entregado', 'cancelado'
  )),
  modalidad TEXT NOT NULL CHECK (modalidad IN ('recoger', 'domicilio')),
  contacto_nombre TEXT NOT NULL,
  contacto_telefono TEXT NOT NULL,
  direccion_entrega JSONB,
  notas_cliente TEXT,
  subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
  costo_domicilio NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (costo_domicilio >= 0),
  total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
  solicitado_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  aceptado_at TIMESTAMPTZ,
  completado_at TIMESTAMPTZ,
  cancelado_at TIMESTAMPTZ,
  cancelado_por UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  motivo_cancelacion TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pedidos_cliente_fecha ON public.pedidos(cliente_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_comercio_estado ON public.pedidos(comercio_id, estado, created_at DESC);

CREATE TABLE IF NOT EXISTS public.pedido_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id UUID NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  producto_id UUID REFERENCES public.productos(id) ON DELETE SET NULL,
  nombre_producto TEXT NOT NULL,
  sku TEXT,
  imagen_url TEXT,
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  cantidad INT NOT NULL CHECK (cantidad > 0),
  total_linea NUMERIC(12,2) NOT NULL CHECK (total_linea >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pedido_items_pedido ON public.pedido_items(pedido_id);

CREATE TABLE IF NOT EXISTS public.pedido_eventos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id UUID NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_tipo TEXT NOT NULL CHECK (actor_tipo IN ('cliente', 'comercio', 'admin', 'sistema')),
  evento TEXT NOT NULL,
  estado_anterior TEXT,
  estado_nuevo TEXT,
  detalle JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pedido_eventos_pedido ON public.pedido_eventos(pedido_id, created_at);

CREATE TABLE IF NOT EXISTS public.api_rate_limit_windows (
  key_hash TEXT NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  hits INT NOT NULL DEFAULT 0 CHECK (hits >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (key_hash, window_start)
);

ALTER TABLE public.ciudades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comercio_miembros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comercio_suscripciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_rate_limit_windows ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.ciudades TO anon, authenticated;
GRANT ALL ON public.ciudades, public.comercio_miembros, public.comercio_suscripciones,
  public.pedidos, public.pedido_items, public.pedido_eventos, public.api_rate_limit_windows
  TO service_role;

CREATE POLICY "Ciudades activas visibles" ON public.ciudades
  FOR SELECT USING (activa = TRUE);

CREATE POLICY "Miembros ven sus comercios" ON public.comercio_miembros
  FOR SELECT TO authenticated USING (
    profile_id = auth.uid()
    OR public.is_comercio_owner(auth.uid(), comercio_id)
    OR public.is_admin(auth.uid())
  );

CREATE OR REPLACE FUNCTION public.is_comercio_member(
  p_user_id UUID,
  p_comercio_id UUID,
  p_roles TEXT[] DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE SQL STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.is_comercio_owner(p_user_id, p_comercio_id)
    OR EXISTS (
      SELECT 1
      FROM public.comercio_miembros cm
      WHERE cm.comercio_id = p_comercio_id
        AND cm.profile_id = p_user_id
        AND cm.activo = TRUE
        AND (p_roles IS NULL OR cm.rol = ANY(p_roles))
    )
$$;
REVOKE ALL ON FUNCTION public.is_comercio_member(UUID, UUID, TEXT[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_comercio_member(UUID, UUID, TEXT[]) TO authenticated, service_role;

CREATE POLICY "Suscripciones visibles para propietario" ON public.comercio_suscripciones
  FOR SELECT TO authenticated USING (
    public.is_comercio_member(auth.uid(), comercio_id) OR public.is_admin(auth.uid())
  );

CREATE POLICY "Cliente ve sus pedidos" ON public.pedidos
  FOR SELECT TO authenticated USING (
    cliente_id = auth.uid()
    OR public.is_comercio_member(auth.uid(), comercio_id)
    OR public.is_admin(auth.uid())
  );

CREATE POLICY "Cliente crea sus pedidos" ON public.pedidos
  FOR INSERT TO authenticated WITH CHECK (cliente_id = auth.uid());

CREATE POLICY "Cliente ve items de sus pedidos" ON public.pedido_items
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.pedidos p
      WHERE p.id = pedido_id
        AND (p.cliente_id = auth.uid() OR public.is_comercio_member(auth.uid(), p.comercio_id) OR public.is_admin(auth.uid()))
    )
  );

CREATE POLICY "Cliente ve eventos de sus pedidos" ON public.pedido_eventos
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.pedidos p
      WHERE p.id = pedido_id
        AND (p.cliente_id = auth.uid() OR public.is_comercio_member(auth.uid(), p.comercio_id) OR public.is_admin(auth.uid()))
    )
  );

CREATE OR REPLACE FUNCTION public.consume_rate_limit(
  p_key_hash TEXT,
  p_limit INT,
  p_window_seconds INT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_window_start TIMESTAMPTZ;
  v_hits INT;
BEGIN
  IF p_limit <= 0 OR p_window_seconds <= 0 THEN
    RAISE EXCEPTION 'Invalid rate limit configuration';
  END IF;

  v_window_start := to_timestamp(floor(extract(epoch FROM NOW()) / p_window_seconds) * p_window_seconds);

  INSERT INTO public.api_rate_limit_windows (key_hash, window_start, hits)
  VALUES (p_key_hash, v_window_start, 1)
  ON CONFLICT (key_hash, window_start)
  DO UPDATE SET hits = public.api_rate_limit_windows.hits + 1, updated_at = NOW()
  RETURNING hits INTO v_hits;

  DELETE FROM public.api_rate_limit_windows
  WHERE window_start < NOW() - INTERVAL '2 days';

  RETURN v_hits <= p_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_rate_limit(TEXT, INT, INT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_rate_limit(TEXT, INT, INT) TO service_role;

CREATE OR REPLACE FUNCTION public.create_pedido(
  p_cliente_id UUID,
  p_comercio_id UUID,
  p_modalidad TEXT,
  p_contacto_nombre TEXT,
  p_contacto_telefono TEXT,
  p_direccion_entrega JSONB,
  p_notas_cliente TEXT,
  p_items JSONB
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_pedido_id UUID;
  v_item JSONB;
  v_producto RECORD;
  v_cantidad INT;
  v_precio NUMERIC(12,2);
  v_subtotal NUMERIC(12,2) := 0;
  v_producto_ids UUID[] := ARRAY[]::UUID[];
BEGIN
  IF p_modalidad NOT IN ('recoger', 'domicilio') THEN
    RAISE EXCEPTION 'Modalidad invalida';
  END IF;
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'El pedido requiere al menos un producto';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = p_cliente_id AND account_status = 'activo'
  ) THEN
    RAISE EXCEPTION 'La cuenta del cliente no esta activa';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.comercios
    WHERE id = p_comercio_id
      AND estado = 'activo'
      AND deleted_at IS NULL
      AND (
        (p_modalidad = 'recoger' AND recogida_disponible = TRUE)
        OR (p_modalidad = 'domicilio' AND domicilio_disponible = TRUE)
      )
  ) THEN
    RAISE EXCEPTION 'El comercio no esta disponible para esta modalidad';
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_cantidad := COALESCE((v_item->>'cantidad')::INT, 0);
    IF v_cantidad <= 0 OR v_cantidad > 99 THEN
      RAISE EXCEPTION 'Cantidad invalida';
    END IF;
    IF (v_item->>'producto_id') IS NULL THEN
      RAISE EXCEPTION 'Producto invalido';
    END IF;
    IF (v_item->>'producto_id')::UUID = ANY(v_producto_ids) THEN
      RAISE EXCEPTION 'No se permite repetir un producto en el pedido';
    END IF;
    v_producto_ids := array_append(v_producto_ids, (v_item->>'producto_id')::UUID);

    SELECT id, nombre, sku, imagen_url, precio_base, precio_oferta, disponible, stock
    INTO v_producto
    FROM public.productos
    WHERE id = (v_item->>'producto_id')::UUID
      AND comercio_id = p_comercio_id
      AND deleted_at IS NULL
    FOR UPDATE;

    IF NOT FOUND OR v_producto.disponible IS NOT TRUE THEN
      RAISE EXCEPTION 'Producto no disponible';
    END IF;
    IF v_producto.stock IS NOT NULL AND v_producto.stock < v_cantidad THEN
      RAISE EXCEPTION 'Stock insuficiente';
    END IF;

    v_precio := COALESCE(v_producto.precio_oferta, v_producto.precio_base);
    v_subtotal := v_subtotal + (v_precio * v_cantidad);
  END LOOP;

  INSERT INTO public.pedidos (
    cliente_id, comercio_id, modalidad, contacto_nombre, contacto_telefono,
    direccion_entrega, notas_cliente, subtotal, costo_domicilio, total
  ) VALUES (
    p_cliente_id, p_comercio_id, p_modalidad, p_contacto_nombre, p_contacto_telefono,
    CASE WHEN p_modalidad = 'domicilio' THEN p_direccion_entrega ELSE NULL END,
    NULLIF(p_notas_cliente, ''), v_subtotal, 0, v_subtotal
  ) RETURNING id INTO v_pedido_id;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_cantidad := (v_item->>'cantidad')::INT;
    SELECT id, nombre, sku, imagen_url, precio_base, precio_oferta, stock
    INTO v_producto
    FROM public.productos
    WHERE id = (v_item->>'producto_id')::UUID;
    v_precio := COALESCE(v_producto.precio_oferta, v_producto.precio_base);

    INSERT INTO public.pedido_items (
      pedido_id, producto_id, nombre_producto, sku, imagen_url, precio_unitario, cantidad, total_linea
    ) VALUES (
      v_pedido_id, v_producto.id, v_producto.nombre, v_producto.sku, v_producto.imagen_url,
      v_precio, v_cantidad, v_precio * v_cantidad
    );

    IF v_producto.stock IS NOT NULL THEN
      UPDATE public.productos SET stock = stock - v_cantidad WHERE id = v_producto.id;
    END IF;
  END LOOP;

  INSERT INTO public.pedido_eventos (pedido_id, actor_id, actor_tipo, evento, estado_nuevo)
  VALUES (v_pedido_id, p_cliente_id, 'cliente', 'pedido_creado', 'solicitado');

  INSERT INTO public.audit_events (actor_id, action, resource_type, resource_id, after_data)
  VALUES (
    p_cliente_id,
    'order.created',
    'pedido',
    v_pedido_id::TEXT,
    jsonb_build_object('comercio_id', p_comercio_id, 'modalidad', p_modalidad, 'items', jsonb_array_length(p_items))
  );

  RETURN v_pedido_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_pedido(UUID, UUID, TEXT, TEXT, TEXT, JSONB, TEXT, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_pedido(UUID, UUID, TEXT, TEXT, TEXT, JSONB, TEXT, JSONB)
  TO service_role;

CREATE OR REPLACE FUNCTION public.actualizar_estado_pedido(
  p_actor_id UUID,
  p_pedido_id UUID,
  p_estado TEXT,
  p_motivo TEXT DEFAULT NULL
)
RETURNS public.pedidos
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_pedido public.pedidos;
  v_estado_anterior TEXT;
  v_actor_role TEXT;
  v_actor_type TEXT;
  v_allowed BOOLEAN := FALSE;
BEGIN
  SELECT * INTO v_pedido FROM public.pedidos WHERE id = p_pedido_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido no encontrado'; END IF;

  SELECT role INTO v_actor_role FROM public.profiles WHERE id = p_actor_id;
  v_actor_type := CASE WHEN v_actor_role IN ('admin', 'super_admin') THEN 'admin'
    WHEN v_pedido.cliente_id = p_actor_id THEN 'cliente' ELSE 'comercio' END;

  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = p_actor_id AND account_status = 'activo'
  ) THEN
    RAISE EXCEPTION 'La cuenta no esta activa';
  END IF;

  v_allowed := public.is_admin(p_actor_id)
    OR public.is_comercio_member(p_actor_id, v_pedido.comercio_id, ARRAY['owner', 'manager', 'atencion'])
    OR (v_pedido.cliente_id = p_actor_id AND p_estado = 'cancelado' AND v_pedido.estado = 'solicitado');
  IF NOT v_allowed THEN RAISE EXCEPTION 'No autorizado'; END IF;

  IF p_estado NOT IN ('aceptado', 'rechazado', 'preparando', 'listo', 'en_camino', 'entregado', 'cancelado') THEN
    RAISE EXCEPTION 'Estado invalido';
  END IF;

  v_estado_anterior := v_pedido.estado;
  IF NOT (
    (v_estado_anterior = 'solicitado' AND p_estado IN ('aceptado', 'rechazado', 'cancelado'))
    OR (v_estado_anterior = 'aceptado' AND p_estado IN ('preparando', 'cancelado'))
    OR (v_estado_anterior = 'preparando' AND p_estado IN ('listo', 'cancelado'))
    OR (v_estado_anterior = 'listo' AND (
      p_estado = 'entregado'
      OR (v_pedido.modalidad = 'domicilio' AND p_estado = 'en_camino')
    ))
    OR (v_estado_anterior = 'en_camino' AND p_estado = 'entregado')
  ) THEN
    RAISE EXCEPTION 'Transicion de pedido no permitida';
  END IF;

  IF p_estado IN ('cancelado', 'rechazado') AND length(trim(coalesce(p_motivo, ''))) < 3 THEN
    RAISE EXCEPTION 'Indique un motivo para cancelar o rechazar el pedido';
  END IF;

  UPDATE public.pedidos SET
    estado = p_estado,
    aceptado_at = CASE WHEN p_estado = 'aceptado' THEN NOW() ELSE aceptado_at END,
    completado_at = CASE WHEN p_estado = 'entregado' THEN NOW() ELSE completado_at END,
    cancelado_at = CASE WHEN p_estado IN ('cancelado', 'rechazado') THEN NOW() ELSE cancelado_at END,
    cancelado_por = CASE WHEN p_estado IN ('cancelado', 'rechazado') THEN p_actor_id ELSE cancelado_por END,
    motivo_cancelacion = CASE WHEN p_estado IN ('cancelado', 'rechazado') THEN NULLIF(p_motivo, '') ELSE motivo_cancelacion END,
    updated_at = NOW()
  WHERE id = p_pedido_id
  RETURNING * INTO v_pedido;

  IF p_estado IN ('cancelado', 'rechazado') THEN
    UPDATE public.productos producto
    SET stock = producto.stock + item.cantidad
    FROM public.pedido_items item
    WHERE item.pedido_id = p_pedido_id
      AND item.producto_id = producto.id
      AND producto.stock IS NOT NULL;
  END IF;

  INSERT INTO public.pedido_eventos (
    pedido_id, actor_id, actor_tipo, evento, estado_anterior, estado_nuevo, detalle
  ) VALUES (
    p_pedido_id, p_actor_id, v_actor_type, 'estado_actualizado',
    v_estado_anterior, p_estado,
    jsonb_build_object('motivo', p_motivo)
  );

  INSERT INTO public.audit_events (actor_id, action, resource_type, resource_id, before_data, after_data)
  VALUES (
    p_actor_id,
    'order.status_changed',
    'pedido',
    p_pedido_id::TEXT,
    jsonb_build_object('estado', v_estado_anterior),
    jsonb_build_object('estado', p_estado, 'motivo', p_motivo)
  );

  RETURN v_pedido;
END;
$$;

REVOKE ALL ON FUNCTION public.actualizar_estado_pedido(UUID, UUID, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.actualizar_estado_pedido(UUID, UUID, TEXT, TEXT)
  TO service_role;

-- Product writes run through authenticated server APIs, where plan limits,
-- validation and audit controls can be enforced consistently.
REVOKE INSERT, UPDATE, DELETE ON public.productos FROM authenticated;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_ciudades_updated_at BEFORE UPDATE ON public.ciudades
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER update_comercio_miembros_updated_at BEFORE UPDATE ON public.comercio_miembros
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER update_comercio_suscripciones_updated_at BEFORE UPDATE ON public.comercio_suscripciones
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER update_pedidos_updated_at BEFORE UPDATE ON public.pedidos
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

INSERT INTO public.ciudades (nombre, slug, departamento, pais_codigo, moneda_codigo)
VALUES ('Barranquilla', 'barranquilla', 'Atlántico', 'CO', 'COP')
ON CONFLICT (slug) DO NOTHING;

UPDATE public.zonas
SET ciudad_id = (SELECT id FROM public.ciudades WHERE slug = 'barranquilla')
WHERE ciudad_id IS NULL;

UPDATE public.comercios
SET ciudad_id = COALESCE(
  (SELECT z.ciudad_id FROM public.zonas z WHERE z.id = comercios.zona_id),
  (SELECT id FROM public.ciudades WHERE slug = 'barranquilla')
)
WHERE ciudad_id IS NULL;
